### ISSUE TITLE
use ES classes for more accurate emulation

### ISSUE THREAD

**Issue by graingert** [Olical/react-faux-dom#117]
eg:

```js
class CSS2Properties {
  setProperty(name, value) {
    this[name] = value;
  }
}

class Element {
  constructor(nodeName, parentNode) {
    this.nodeName = nodeName;
    this.parentNode = parentNode;
    this._style = new CSS2Properties();
  }

  get style() {
    return this._style;
  }
}
```

**Comment by graingert** [comment]
and like webpack or etc.

**Comment by Olical** [comment]
I guess because it's already being run through webpack it wouldn't be that hard to do. I just didn't want to incur the overhead(ache) of transpiling JavaScript. I'm open to merging PRs for this, but I have no desire to change to a newer syntax just for stylistic reasons.

I realise that class construction is arguably better when you use actual `class`es, _but_ is it actually an issue for anyone right now? If not, maybe it's not worth the risk of breaking things.

I stuck to ES5 just to keep things simple since I didn't require the newer parts of the language spec.

**Comment by graingert** [comment]
It makes life easier to add getters and setters

**Comment by Olical** [comment]
Going to close this one since it's not a show stopper and I'm just trying to keep up with maintenance at the moment.
