### ISSUE TITLE
README may need update

### ISSUE THREAD

**Issue by geekplux** [Olical/react-faux-dom#139]
I see the part **Limitations** in README:

> ## Limitations
> This means things that require mutation of the DOM, such as D3's animations, zooming, dragging and brushing will not work.

But now animations, brush, zoom, etc. seems all supported (I found some demos or issues), so it would better be updated, I think.

**Comment by Olical** [comment]
Those limitations are intended for the normal usage of the library, I've continually had issues saying "why doesn't brush work" when they're using the normal immutable flow. Yes, I do believe the higher order component allows some of these things to work (maybe all?) but I have never used it.

This warning is there for people who try to use the library under the misconception that'll it'll work just like regular D3 out of the box. It's not that RFD supports these things now as such but that there is a special workaround that was contributed to the project for people to use if they really need it.

I still advice that you should just prevent React updates in that part of your tree and use regular D3 mounted on that node using the lifecycle hooks if you need to do a lot of complex mutation and animations. But that's just my personal opinion and it could be outdated since I'm barely touching frontend development these days.

**Comment by geekplux** [comment]
Thanks for the nice reply. hope RFD will be better 👍
