### ISSUE TITLE
D3 Animations

### ISSUE THREAD

**Issue by pmajmudar** [Olical/react-faux-dom#14]
Hey,

Great work on the library - it worked first time for me, hardly any code required to get my D3 chart rendering in react!

The only issue I have is that animation doesn't work. I know you mentioned on your blog that this is something you might work on in the future - any update on this?

Cheers,

Prash

**Comment by Olical** [comment]
That's excellent! Always happy to hear that it's working for more people.
It's certainly made a bunch of my work easier, which is why I built it!

I'm not too sure if I'll be able to get animation working the D3 way yet,
because it relies on a lot of state. Right now using a React animation
library is probably the best approach. If we can work out how to pass the
current time into D3 instead of leaving it up to state then we should be
able to get it working. Maybe it'll require a little D3 plugin to bridge
the gap. I'm not sure yet.

But this is next on my list after finishing my events overhaul which should
make addEventListener and mouse interaction work perfectly. Right now it's
not transparent, it's clearly React events, not DOM events.

I'll investigate as soon as the events are cleaned up. I'm actually on
holiday for a few more days and returning Sunday, so I haven't had a chance
to work on much.

**Comment by davidjnelson** [comment]
I love what you're doing with this project!  Thank you :-)  Animation support would be fantastic.  I'm new to d3.  What sort of d3 plugin did you have in mind?  Maybe I could submit a PR if I understood it better?  Cheers!

**Comment by Olical** [comment]
I'm afraid I'm going to close this (among other issues), the reason is stated in the new [limitations section](https://github.com/Olical/react-faux-dom#limitations) in the readme (PR #30). This is essentially a question of state management which is [illustrated in my lab](http://lab.oli.me.uk/react-faux-dom-state/) with a simple example. The principal is essentially the same though!

--------------

The above was just a copy paste between state related issues, this is specific: I don't think D3 animation will work out of the box, you should just use React animation libraries which are arguably better. With regards to a plugin, I meant something that would replace the internal D3 animation tooling with something that created React animations. I kind of doubt it'd work though.
