### ISSUE TITLE
Backbone View toReact?

### ISSUE THREAD

**Issue by haohcraft** [Olical/react-faux-dom#17]
Hi Oliver,

Most recently I have been in a situation where I need to "convert" the BackboneView to React views. I am wondering if you have any experience of using this project's idea to convert the BackboneView. 

Initially, I have to make a "BackboneView | React View|BackboneView | React View" type of component in order to reuse the existing well-maintained in-house BackboneView components, but gradually I found such sandwich format would run into some issue, for example,  when we tried to insert the BackboneView component during the `componentDidMount` and after the state changed the Backbone component would disappear. Arguably we could re-insert the Backbone View component in a hacky way but not ideal. And rewriting the whole Backbone Component codebase is way more time-consuming on our side.

Thanks in advance,

Hao

**Comment by Olical** [comment]
Hello! That's an interesting problem and a good second use case for this library. I would imagine that it would work fine for the basics, but you will soon realise that it's lacking a lot of key DOM features and methods. I would recommend giving it a go and potentially adding functions if they're missing and fairly trivial.

You would simply call `new ReactFauxDOM.Element()` and assign it to `el` (I think? I've never used backbone professionally). Then proceed to add listeners (which *should* work!) etc. If you were using jQuery or something you could very easily encounter issues since it will use a lot of DOM methods, some of which don't exist yet but can easily be added.

To try this out you can take a backbone view, let's say a user from a list of users, and render it inside of a React component render function with a faux DOM element. In the exact same way it works with D3. When the props change you re-render the backbone element with the new data.

The only problem I can think of, which could be a big one, is templates. That will just generate a string and paste it into the DOM node with `innerHtml` I presume. I don't actually parse that string, I leave that up to React, so it may mean I need to support HTML parsing of some kind for Backbone + Templates to work. Unless the templates produce DOM nodes? In which case it may just work because I have some support for mixed trees of "real" and "faux" DOM nodes.

All we can do is try it out and see how far we get before we hit errors :)

**Comment by haohcraft** [comment]
I will give a try. Thanks for reply.

**Comment by Olical** [comment]
Closing this now since it's been a while. I hope you got it working! If you need changes then I'd be more than happy to review a PR. If you got it working it'd be cool to share with the community too :)
