### ISSUE TITLE
error with nvd3

### ISSUE THREAD

**Issue by arolson101** [Olical/react-faux-dom#45]
I'm trying to use with nvd3, and I get an error "TypeError: Cannot read property 'replace' of undefined(…)" on the line ```var fontSize = parseInt(svgTextElem.style("font-size").replace("px",""), 10);```

I can provide code if needed

**Comment by Olical** [comment]
Well this just looks like `font-size` isn't set on the element? There are limitations to JavaScript reading styles from elements unless they're set on the inline style. Maybe you need to investigate `getComputedStyle`?

**Comment by arolson101** [comment]
I haven't actually tested, but it looks like a regular DOM element would have an empty string font-size in this situation.

Are you saying that where react-faux-dom differs in implementation from the actual dom, the onus is on the client to provide a workaround?

**Comment by Olical** [comment]
Yes, if you took a native DOM node and used `.style.fontSize` you'd probably get undefined too. The faux DOM is in keeping with this style. If you haven't set the font-size before this line you mentioned, it will be undefined.

**Comment by arolson101** [comment]
Nope, empty string
```
> document.createElement("div").style.fontSize
< ""
```

**Comment by Olical** [comment]
I'm going to need some more context around this to help I'm afraid. I might
be able to help, but I don't know the context yet.

**Comment by arolson101** [comment]
Here's an example adapted from https://nvd3-community.github.io/nvd3/examples/lineChart.html

```
export const CurrencyChart = () => {
  // Wrapping in nv.addGraph allows for '0 timeout render', stores rendered charts in nv.graphs, and may do more in the future... it's NOT required
  var chart;
  var data;
  var randomizeFillOpacity = function() {
      var rand = Math.random(0,1);
      for (var i = 0; i < 100; i++) { // modify sine amplitude
          data[4].values[i].y = Math.sin(i/(5 + rand)) * .4 * rand - .25;
      }
      data[4].fillOpacity = rand;
      chart.update();
  };

  chart = nv.models.lineChart()
      .options({
          transitionDuration: 300,
          useInteractiveGuideline: true
      })
  ;
  // chart sub-models (ie. xAxis, yAxis, etc) when accessed directly, return themselves, not the parent chart, so need to chain separately
  chart.xAxis
      .axisLabel("Time (s)")
      .tickFormat(d3.format(',.1f'))
      .staggerLabels(true)
  ;
  chart.yAxis
      .axisLabel('Voltage (v)')
      .tickFormat(function(d) {
          if (d == null) {
              return 'N/A';
          }
          return d3.format(',.2f')(d);
      })
  ;
  data = sinAndCos();

  const svg = ReactFauxDOM.createElement('svg');
  d3.select(svg)
      .datum(data)
      .call(chart);
  nv.utils.windowResize(chart.update);

  function sinAndCos() {
      var sin = [],
          sin2 = [],
          cos = [],
          rand = [],
          rand2 = []
          ;
      for (var i = 0; i < 100; i++) {
          sin.push({x: i, y: i % 10 == 5 ? null : Math.sin(i/10) }); //the nulls are to show how defined works
          sin2.push({x: i, y: Math.sin(i/5) * 0.4 - 0.25});
          cos.push({x: i, y: .5 * Math.cos(i/10)});
          rand.push({x:i, y: Math.random() / 10});
          rand2.push({x: i, y: Math.cos(i/10) + Math.random() / 10 })
      }
      return [
          {
              area: true,
              values: sin,
              key: "Sine Wave",
              color: "#ff7f0e",
              strokeWidth: 4,
              classed: 'dashed'
          },
          {
              values: cos,
              key: "Cosine Wave",
              color: "#2ca02c"
          },
          {
              values: rand,
              key: "Random Points",
              color: "#2222ff"
          },
          {
              values: rand2,
              key: "Random Cosine",
              color: "#667711",
              strokeWidth: 3.5
          },
          {
              area: true,
              values: sin2,
              key: "Fill opacity",
              color: "#EF9CFB",
              fillOpacity: .1
          }
      ];
  }

  return svg.toReact();
};
```

**Comment by Olical** [comment]
I'm really not sure if I can help here I'm afraid. `.style` just doesn't work like that.

Unless you set `font-size` on the element directly through D3, it will be undefined. Stylesheets don't allow you to access their values through `.style`. I hope you solved your issue or found a way around though! :smile:

**Comment by nextminds** [comment]
Hi @Olical,

Great work on react-faux-dom! I'm having the same problem as @arolson101.

> Yes, if you took a native DOM node and used .style.fontSize you'd probably get undefined too. 

anyNode.style.fontSize should return an empty string if the fontSize is not set. The NVD3 lib expects this. It would be great if react-faux-dom could mimmick this behaviour. https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-ElementCSSInlineStyle

There doens't seem to be a workaround, because you're not able to directly set the fontSize of the label in nvd3 (it expects you to use css).

**Comment by Olical** [comment]
@nextminds Defaulting to an empty string makes sense to me, if you'd like to open an issue or PR I'll get around to it soon.

**Comment by dchambers** [comment]
Ooh, this is timely! I've just run into the same issue :smile:

Interestingly, for me, I didn't even get as far as seeing this error until after I'd patched D3 to use the version of `getComputedStyle()` on the `window` associated with the element, rather than the global `window` object. I did this by changing this line:

~~~js
if (n < 2) return d3_window.getComputedStyle(this.node(), null).getPropertyValue(name);
~~~
 
to this:

~~~js
var win = this.node().ownerDocument.defaultView;
if (n < 2) return win.getComputedStyle(this.node(), null).getPropertyValue(name);
~~~

This would seem like the kind of change that one might reasonably expect D3 to accept a pull-request for, except it's not clear to me why D3 is maintaining its own reference to the `window` object rather than referencing it directly.
