### ISSUE TITLE
How to approach animations and compositions with react-faux-dom?

### ISSUE THREAD

**Issue by kennetpostigo** [Olical/react-faux-dom#49]
I'm working on a couple components using `react-faux-dom`. It literally just works out the box thank you for this. As it stands I have a line chart, bar chart, area chart, scatter-plot etc. However all of these each come with their own x/y-axis, grid, legend. I don't want to duplicate the code, as it makes more sense to abstract these out of the different charts into their own components. I'm not exactly sure how to go about composing the x/y-axis, legend, and the chart chosen together.

Some code may make more sense:
```js
   // What I have in my head
  <XYAxis grid={true}>
    <LineChart {...}/>
    <Legend  {...} />
  </XYAxis>

  <XYAxis grid={false}>
    <BarChart {...}/>
    <Legend  {...} />
  </XYAxis>
```
I'm not sure exactly how to go about this in `react-dom-faux `, if you've done something like this with your library I'd like to know what approach might have worked best for you.

I'd also like to add Animations using React Motion, for things like updates in the data set, filtering data, tool-tips, etc. What would you suggest be the best approach for adding animations with 'react-faux-dom'?

I wouldn't mind adding some more example docs for your library as It has really made my life easier. If theres anything specific you want to add but haven't had the time let me know 👍🏽

**Comment by kennetpostigo** [comment]
My confusion lies on how to append the Elements that the `LineChart` component renders onto the Elements the the `XYAxis` renders.

**Comment by Olical** [comment]
I can't say I've done this myself just yet, but I can offer some pointers and we can discuss further. I really hope the library has helped you so far though!

So one interesting property about the faux DOM is that it can contain React elements like in [this test](https://github.com/Olical/react-faux-dom/blob/master/test/react.js#L43-L55). So you can have a component that depends on another component and you can embed it into the faux DOM just like you would the normal React tree.

So, you could compose them by adding the build elements to a faux DOM and returning that. Although, composing through JSX works equally well, they are just children of the `XYAxis` component then.

Within the `BarChart` you could embed the legend / `XYAxis` for example, or you could even subclass the shared graph stuff.

It's entirely up to you, this is a React design question more than anything :)

In a tree that contains ReactFauxDOM it's only faux DOM within one of the render methods, before that it's React and after that it's React because of the `.toReact` calls.

**Comment by kennetpostigo** [comment]
@Olical Thank you for the response, I was thinking about this and I think I found a solution to how to make this work well, I'm going to whip together some code and post my results. How would you go about adding animations with a library with react-motion? I'm also going to write up some docs and do a PR by tomorrow hopefully.

**Comment by Olical** [comment]
Well you should be able to use `react-motion` as is, since it just wraps existing components, right? (I haven't actually used it but I know about it)

You should be able to wrap the rendered React component as you'd wrap any other. If your chart takes a while to render though this could be quite slow. This is where [these mixins](https://github.com/Olical/react-faux-dom/tree/master/examples/animate-d3-with-mixin) come in, they give you efficient animations, even animations from D3. They're a bit of a workaround though, if wrapping your component with `react-motion` is enough for you, then try that :)

**Comment by kennetpostigo** [comment]
Okay, will check those out 😀

**Comment by kennetpostigo** [comment]
Sorry for the lengthy comment 😥

So I got a working prototype, the code below will render A LineChart. The `XYAxis` component has a variable called `axes`, this will be the `react-faux-dom` element. From there I append the x/y axis to it with D3. However I was thinking about how to `append` or `render` the `LineChart` _lines_ onto the `axes` from `XYAxis`, What I did was clone the `this.props.children` and then pass the `props`, `g`, and the  `axes` variable which is the root  `react-faux-element` to the cloned `LineChart` component. Inside of `LineChart` I append the lines to the prop `g` and then return the prop 'axes' (the root `react-faux-dom` element). Lastly, the XYAxis component will render `children` (the cloned LineChart). 

```js
// This draws a Axis with a grid
class XYAxis extends React.Component {
  ...
  scaleLinear () {
    ...
    return {xScale, yScale, innerH, innerW};
  }
  makeGrid () {
     ...
    return {xAxis, yAxis, xScale, yScale};
  }

  render () {
    const { data, width, height, gridLines, x, y } = this.props,
          grid = this.makeGrid(),
          xScale = grid.xScale,
          yScale = grid.yScale,
          xAxis = grid.xAxis,
          yAxis = grid.yAxis,
          innerW = width - 60,
          innerH = height - 60,
          gridLineType = (gridLines !== 'solid') ? '3,3' : '';

    var axes = d3.select(ReactFauxDOM.createElement('svg'))
        .attr('width', width)
        .attr('height', height);

    var g = axes.append('g')
        .attr('class', 'axes')
        .attr('transform', `translate(50, 20)`);

    g.append("g")
        .attr('class', 'x axis')
        .attr('transform', `translate(0, ${innerH})`)
        .call(grid.xAxis)
        .append('text')
        .attr('class', 'label')
        .attr('x', innerW)
        .attr('y', -6)
        .style('text-anchor', 'end')
        .text(x);

    g.append('g')
        .attr('class', 'y axis')
        .call(grid.yAxis)
        .append('text')
        .attr('transform', 'rotate(-90)')
        .attr('y', 6)
        .attr('dy', '.71em')
        .style('text-anchor', 'end')
        .text(y);
    var children = React.cloneElement(this.props.children, { data, width, height, xAxis, yAxis, xScale, yScale, g, axes});
    return children;
  }
}

// Renders the LineChart and XYAxis
class LineChart extends React.Component {
  render () {
    const { data, width, height, grid, xAxis, yAxis, xScale, yScale, g, axes} = this.props;

    var line = d3.svg.line()
        .interpolate("monotone")
        .x((d) => xScale(d.x))
        .y((d) => yScale(d.y));

    g.append('path')
        .datum(data)
        .attr('class', 'line')
        .attr('d', line);

    g.selectAll('circle')
      .data(data)
      .enter().append('circle')
      .attr('class', 'circle')
      .attr('cx', (d) => xScale(d.x))
      .attr('cy', (d) => yScale(d.y))
      .attr('r', 3);

    return axes.node().toReact();
  }
}

//Render
      <XYAxis width={350}
              height={300}
              data={data2}
              grid={true}
              x={'x'}
              y={'y'}
              gridLines={'solid'}>
        <LineChart/>
      </XYAxis>
```

Side note, I was also thinking about `appendChild` within LineChart but realized it can't append child within `LineChart` because it hasn't been rendered. 

Anyway this is what I came up with, it's brittle and wont work with multiple children passed into `XYAxis`. If you have any thought about alternative solutions lmk. Sorry for the lengthy comment again 😅.

**Comment by kennetpostigo** [comment]
@Olical So I got this working well now with arbitrary amount of charts nested the the `XYAxis` component and the charts and `XYAxis` component can render separately. 👍🏽

**Comment by kennetpostigo** [comment]
I do! If you open one up all add some stuff in there, probably sometime before tuesday next week.

**Comment by Olical** [comment]
[The wiki](https://github.com/Olical/react-faux-dom/wiki) is freely editable by anyone, so go for it! :)

**Comment by kennetpostigo** [comment]
@Olical thanks will do!
