### ISSUE TITLE
getBoundingClientRect returns undefined

### ISSUE THREAD

**Issue by stocksp** [Olical/react-faux-dom#56]
Use the example code (animate-d3-with-mixin), put a break point on line 88.
In the debugger execute
`rect[0][0].getBoundingClientRect()`
returns undefined.
Stepping into Element.prototype.getBoundingClientRect
I see in the first line that the Element doesn't have a component
```
if (!this.component) {  
  return undefined  
  } 
```

not sure what that means(no component)  or if I'm using the new api correctly....

**Comment by alexyuly** [comment]
Hi @stocksp, `this.component` will hold a reference to an Element's associated DOM component, but only *after* React has mounted the component. This reference is used to call `getBoundingClientRect`.

I think perhaps in [the example code you mentioned](https://github.com/Olical/react-faux-dom/blob/master/examples/animate-d3-with-mixin/index.js), that `rect` variable is a D3 selection on a faux Element that hasn't been mounted yet. In that case, `getBoundingClientRect`  would return `undefined`, by design.

Does that help at all?

**Comment by stocksp** [comment]
Ugh!,   it means I'll have to redo/rethink a bunch of nasty D3 code as it uses the geometry obtained from the bounding box to compute the size and position of the chart components all before React gets to mount it.....

**Comment by tomcardoso** [comment]
Just to make sure I understand this: are there any hacks I can perform to get access to `getBoundingClientRect` figures? I'm in a similar boat to @stocksp with D3 code that relies on `getBoundingClientRect` to position axes and tooltips. Not easily refactorable as it's part of a larger charting library…

**Comment by Olical** [comment]
Nope, that function requires the browser to already have rendered the node somewhere. It needs to take into account all other elements on the page and CSS, this isn't something that can be done within the faux DOM.

You'll have to wait for it to mount then grab the node of the component, then you can ask for the bounding client rect on that real node.
