### ISSUE TITLE
Event listener options are not supported

### ISSUE THREAD

**Issue by alexyuly** [Olical/react-faux-dom#79]
EventTarget.addEventListener supports a third parameter called `options` or `useCapture` (see https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener).

However, this package's Element.addEventListener does not account for a third parameter:
https://github.com/Olical/react-faux-dom/blob/master/lib/Element.js#L138

Is there any way to add event listeners with options? Any thoughts on this? Can I implement this?

**Comment by Olical** [comment]
If it's required, someone (or myself) can add it, sure. I don't think it's hard. As far as I'm aware, D3 does not use this for it's event methods, so I didn't implement it. I only implemented the features that were required for D3 to function with the intention that more things could be added as people tried to use it with other DOM libraries. If you need 100% parity, `jsdom` already has that solved :smile:

**Comment by Olical** [comment]
Actually going to close this for now because it's not exactly an issue. Well, for me or you. If anyone encounters errors because of this, sure. If you want to implement it, feel free! Not sure how to go about it because you essentially have to translate `useCapture` to the React event equivalent (of which there may not be). Thanks for raising it though!

**Comment by alexyuly** [comment]
Thanks! I may have a use case that requires it... if so I'll submit a PR and we can discuss.
