### ISSUE TITLE
using d3.zoom results in react warning of unknown prop

### ISSUE THREAD

**Issue by davidtzoor** [Olical/react-faux-dom#82]
Hi,
I am using `react-faux-dom` to generate a `d3.forceSimulation` and tried to use the `d3.zoom` module as well.

I have the following code:

```
const root = new ReactFauxDOM.createElement('div');

this.svg = select(root).append('svg')
	.attr('width', '100%')
	.attr('height', '600px')
	.call(zoom().scaleExtent([1/2, 8]).on('zoom', this.zoomed))
	.append('g');

...
return root.toReact();
```

And I am getting the following warning in the console:
`Warning: Unknown prop `dblclick` on <svg> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

Any idea how to work around it?

**Comment by Olical** [comment]
If you're using a force simulation it'll try to mutate the DOM, will it not? It uses animations, as far as I know. That won't work within a stateless snapshot of some D3. There also appears to be weird interactions between React and dblclick https://stackoverflow.com/questions/25777826/onclick-works-but-ondoubleclick-is-ignored-on-react-component

**Comment by davidtzoor** [comment]
In that case, do you have any suggestions how to approach this problem?

**Comment by Olical** [comment]
If you want to do anything that uses physics, animations or mutation of the DOM in any way, I'd just fall back to the original way people got around this https://stackoverflow.com/questions/21903604/is-there-any-proper-way-to-integrate-d3-js-graphics-into-facebook-react-applicat

This library exists for simple components (charts, icons etc) that don't want to introduce the stateful nature of D3 into their application. You can keep your component pure, but you sacrifice a lot of the power of D3 because it needs to mutate the DOM and hold state.

**Comment by davidtzoor** [comment]
Thanks 😄
