### ISSUE TITLE
Support for JSX

### ISSUE THREAD

**Issue by zhenyulin** [Olical/react-faux-dom#94]
following #34 

```
const axisGroup = Faux.createElement('g');
axisGroup.setAttribute('class', className);
axisGroup.setAttribute('transform', transform);
const axisDom = select(axisGroup).call(axis);
return  axisDom.node().toReact();
```

I'm getting patterns like this at the moment, so continuing on this topic, I'm thinking to get JSX to create the base element, while utilise D3 to create the children. The spread attributes feature has been specifically useful to clean up my code.

```
const axisGroup = Faux(<g {...{className, transform}} />);
const axisDom = select(axisGroup).call(axis);
return axisDom.node().toReact();
```

**Comment by Olical** [comment]
I'm not sure how this would work since you'd need to convert the React elements to a react-faux-dom element, I'm not sure if that's even possible without losing some information. I see why you'd want this, but my previous statement of "going JSX -> faux-dom -> JSX" for the sake of slightly different syntax just isn't worth it for me. I am also trying to change this library as little as possible since it's quite simple at the moment and I'd like to keep it that way.

Simplicity keeps it easy to learn, use and maintain. The less features, the better :smile: if you can think of an easy way to implement this then I'd consider it, but I can't right now. It would just introduce too much complexity for a little more ease of use in some cases.

**Comment by Olical** [comment]
I'm going to close this for now since I don't think it's possible in an elegant way, but I will consider it if someone can show me a nice way of doing it.
